import uuid
import json
from app.core.llm import ask_llm_json
from app.core.config import settings
from app.services.audit import log_event

ROUTING_FILE = settings.DATA_DIR / "routed_findings.json"

ROLES = ["maintenance_lead", "compliance_officer", "safety_officer", "plant_manager"]

CLASSIFY_PROMPT = """A finding has been generated by an industrial AI system. Determine which
role(s) should be notified about it, and why.

FINDING: {finding_text}
FINDING SOURCE: {source_feature}

Available roles: maintenance_lead, compliance_officer, safety_officer, plant_manager

Return JSON:
{{
  "route_to": ["list of relevant roles from the available list above"],
  "priority": "low|medium|high",
  "routing_reason": "one sentence explaining why these roles need to see this"
}}
"""


def _load_inbox() -> list[dict]:
    if not ROUTING_FILE.exists():
        return []
    return json.loads(ROUTING_FILE.read_text())


def _save_inbox(items: list[dict]):
    ROUTING_FILE.write_text(json.dumps(items, indent=2))


def route_finding(finding_text: str, source_feature: str) -> dict:
    result = ask_llm_json(
        prompt=CLASSIFY_PROMPT.format(finding_text=finding_text, source_feature=source_feature),
        system="You are a precise routing classifier for industrial safety/compliance findings.",
        feature="routing",
    )

    entry = {
        "id": f"route_{uuid.uuid4().hex[:8]}",
        "finding": finding_text,
        "source_feature": source_feature,
        "route_to": result.get("route_to", []),
        "priority": result.get("priority", "medium"),
        "routing_reason": result.get("routing_reason", ""),
        "acknowledged": False,
    }
    inbox = _load_inbox()
    inbox.append(entry)
    _save_inbox(inbox)

    log_event(feature="routing", action="finding_routed",
              detail={"route_to": entry["route_to"], "priority": entry["priority"]})

    return entry


def get_inbox_for_role(role: str) -> list[dict]:
    inbox = _load_inbox()
    return [item for item in inbox if role in item.get("route_to", [])]


def acknowledge_finding(finding_id: str) -> bool:
    inbox = _load_inbox()
    for item in inbox:
        if item["id"] == finding_id:
            item["acknowledged"] = True
            _save_inbox(inbox)
            return True
    return False


def get_all_routed() -> list[dict]:
    return _load_inbox()
